name: Extract and Release

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM_URL"
        default: "https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS3.0.2.0.WNRINXM/garnet_in_global_images_OS3.0.2.0.WNRINXM_20260320.0000.00_16.0_in_fd98e69088.tgz"
      DEVICE_NAME:
        description: "DEVICE_NAME"
        default: "garnet"
      EXTRACTED_FILES:
        description: "EXTRACTED_FILES"
        default: "boot.img, dtbo.img, product.img, system.img, system_ext.img"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Download ROM
        run: curl -LJO "${{ github.event.inputs.ROM_URL }}"

      - name: Extract ROM
        run: |
          FILE=$(find . -maxdepth 1 -type f \( -name "*.zip" -o -name "*.tgz" \) | head -1)

          echo "ZIP_FILE=$FILE" >> $GITHUB_ENV
          echo "ZIP_FILE_SHA256=$(sha256sum "$FILE" | cut -d' ' -f1)" >> $GITHUB_ENV

          if [[ $FILE == *.tgz ]]; then
              tar -xzf "$FILE"
              cp "$(find . -type d -name images | head -1)"/*.img .
          else
              chmod +x .github/scripts/android-ota-extractor
              .github/scripts/android-ota-extractor "$FILE"
          fi

          find . -maxdepth 1 -type f -size +2G -delete

      - name: GH Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.EXTRACTED_FILES }}
          name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
            Extracted files: ${{ github.event.inputs.EXTRACTED_FILES }}
            SHA256: ${{ env.ZIP_FILE_SHA256 }}
